### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ghost** [Eccenux/WebExt-SearchAutocomplete#1]
All right? Your extension is dead? If not, I find your plugin very useful and is the unique option today, and  I have suugestions:

Add a setting to put an default "auto complete service" and add some presets like google, bing, 

An setting to change SA shortcut, if not possible, I suggest you change to simple "S" is even more short and easy instance, "s en word"

options to search bookmarks and history every time in every search engine or if user want, using shortcuts, 

Setting to number of suggetions displayed

feature to add engine directly from an field using context menu

setting to remove the first line "type in your search engine..."

thanks...

**Comment by Eccenux** [comment]
Yes, I'm alive ;-). Sadly I cannot do most things you ask because of browser restrictions. More details below.

> Add a setting to put an default "auto complete service" and add some presets like google, bing,

Browsers do not allow replacing search mechanism. You have to use a keyword (`sa` is the keyword for my extension).

> An setting to change SA shortcut, if not possible, I suggest you change to simple "S" is even more short and easy instance, "s en word"

This is not allowed by browsers. Each browser extension can only use a single opening keyword. Would love to introduce more of them, but that's sadly not possible.

> options to search bookmarks and history every time in every search engine or if user want, using shortcuts,

This is actually handled by Firefox. For each phrase you enter you should get an autocomplete from the extension and some extra stuff from bookmarks and history. And that brings us to your next suggestion...

> Setting to number of suggetions displayed

This is not allowed by browsers. AFAIK both Firefox and Chrome doesn't allow extension developers to change the rules. They just only display 6 results from the extension and all other are from history.

If you want you can file a suggestion to [bugzilla.mozilla.org](https://bugzilla.mozilla.org/) to Firefox. If you will please let me know. I would be happy to vote for it :-)

> feature to add engine directly from an field using context menu

That is sadly not possible or at least not feasible. I think I could add a search but would have to know a specification for autocomplete. Autocomplete can and usually works in a very different way then standard search.

> setting to remove the first line "type in your search engine..."

I can change the text but I cannot remove it. This is something that is displayed by the browser.

If you would like to know more technical stuff about what is possible then the API for suggestion is called [omnibox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox). The first suggestion is created by [setDefaultSuggestion](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox/setDefaultSuggestion) method. The API is not easy to follow (probably because it was made by Google ;-)), but the limitation on the number of  items (6 suggestions only) is mentioned in the description of [onInputChanged](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/omnibox/onInputChanged#addListener_syntax) event.

**Comment by ghost** [comment]
ok, thanks
